// AUTO-GENERATED by scripts/generate-seed.mjs from docs/research/*.csv.
// Do not edit by hand — run `npm run gen:seed` after changing the CSVs.
import { ActivityCard } from '../models/activity-card';

export const SEED_ACTIVITY_CARDS: ActivityCard[] = [
  {
    "equipmentId": "druckschlauch-b",
    "difficulty": "Leicht",
    "taboo": [
      "Schlauch",
      "Wasser",
      "Rollen",
      "Kupplung"
    ]
  },
  {
    "equipmentId": "druckschlauch-c",
    "difficulty": "Leicht",
    "taboo": [
      "Schlauch",
      "Angriff",
      "Rohr",
      "Kupplung"
    ]
  },
  {
    "equipmentId": "steckleiter",
    "difficulty": "Leicht",
    "taboo": [
      "Leiter",
      "Steigen",
      "Teile",
      "Fenster"
    ]
  },
  {
    "equipmentId": "klappleiter",
    "difficulty": "Leicht",
    "taboo": [
      "Leiter",
      "Klappen",
      "Steigen"
    ]
  },
  {
    "equipmentId": "verteiler",
    "difficulty": "Leicht",
    "taboo": [
      "Verteilen",
      "Rohre",
      "Drei",
      "Niederschraubventil"
    ]
  },
  {
    "equipmentId": "standrohr",
    "difficulty": "Leicht",
    "taboo": [
      "Hydrant",
      "Wasser",
      "Unterflur",
      "Schlüssel"
    ]
  },
  {
    "equipmentId": "hohlstrahlrohr",
    "difficulty": "Leicht",
    "taboo": [
      "Rohr",
      "Sprühen",
      "Wasser",
      "Strahl"
    ]
  },
  {
    "equipmentId": "pulverloescher",
    "difficulty": "Leicht",
    "taboo": [
      "Feuer",
      "Löschen",
      "Pulver",
      "Schaum"
    ]
  },
  {
    "equipmentId": "handscheinwerfer",
    "difficulty": "Leicht",
    "taboo": [
      "Licht",
      "Lampe",
      "Leuchten",
      "Dunkel"
    ]
  },
  {
    "equipmentId": "verkehrsleitkegel",
    "difficulty": "Leicht",
    "taboo": [
      "Straße",
      "Absperren",
      "Orange",
      "Hütchen"
    ]
  },
  {
    "equipmentId": "feuerwehrleine",
    "difficulty": "Leicht",
    "taboo": [
      "Seil",
      "Knoten",
      "Sichern",
      "Beutel"
    ]
  },
  {
    "equipmentId": "feuerwehreimer",
    "difficulty": "Leicht",
    "taboo": [
      "Wasser",
      "Tragen",
      "Henkel"
    ]
  },
  {
    "equipmentId": "kuebelspritze",
    "difficulty": "Leicht",
    "taboo": [
      "Wasser",
      "Eimer",
      "Pumpen",
      "Kleinbrand"
    ]
  },
  {
    "equipmentId": "spaten",
    "difficulty": "Leicht",
    "taboo": [
      "Graben",
      "Erde",
      "Schaufel"
    ]
  },
  {
    "equipmentId": "brechstange",
    "difficulty": "Leicht",
    "taboo": [
      "Hebeln",
      "Eisen",
      "Aufbrechen"
    ]
  },
  {
    "equipmentId": "rettungsaxt",
    "difficulty": "Leicht",
    "taboo": [
      "Hacken",
      "Beil",
      "Schlagen",
      "Holz"
    ]
  },
  {
    "equipmentId": "atemschutzmaske",
    "difficulty": "Leicht",
    "taboo": [
      "Gesicht",
      "Atmen",
      "Luft",
      "Rauch"
    ]
  },
  {
    "equipmentId": "pressluftatmer",
    "difficulty": "Leicht",
    "taboo": [
      "Flasche",
      "Rücken",
      "Atmen",
      "Luft"
    ]
  },
  {
    "equipmentId": "rettungsdecke",
    "difficulty": "Leicht",
    "taboo": [
      "Gold",
      "Silber",
      "Wärmen",
      "Patient"
    ]
  },
  {
    "equipmentId": "verbandkasten",
    "difficulty": "Leicht",
    "taboo": [
      "Erste Hilfe",
      "Pflaster",
      "Wunde",
      "Koffer"
    ]
  },
  {
    "equipmentId": "motorsaege",
    "difficulty": "Leicht",
    "taboo": [
      "Sägen",
      "Kette",
      "Baum",
      "Benzin"
    ]
  },
  {
    "equipmentId": "warnblitzleuchte",
    "difficulty": "Leicht",
    "taboo": [
      "Blinken",
      "Gelb",
      "Warnen",
      "Licht"
    ]
  },
  {
    "equipmentId": "saugschlauch-a",
    "difficulty": "Leicht",
    "taboo": [
      "Saugen",
      "Offenes Gewässer",
      "Starr",
      "Kupplung"
    ]
  },
  {
    "equipmentId": "schlauchtragekorb",
    "difficulty": "Leicht",
    "taboo": [
      "Schlauch",
      "Korb",
      "Tragen",
      "C"
    ]
  },
  {
    "equipmentId": "bolzenschneider",
    "difficulty": "Leicht",
    "taboo": [
      "Schneiden",
      "Schloss",
      "Kette",
      "Griffe"
    ]
  },
  {
    "equipmentId": "waermebildkamera",
    "difficulty": "Mittel",
    "taboo": [
      "Kamera",
      "Wärme",
      "Hitze",
      "Bildschirm"
    ]
  },
  {
    "equipmentId": "halligan-tool",
    "difficulty": "Mittel",
    "taboo": [
      "Tür",
      "Hebeln",
      "Aufbrechen",
      "Werkzeug"
    ]
  },
  {
    "equipmentId": "kabeltrommel",
    "difficulty": "Mittel",
    "taboo": [
      "Strom",
      "Kabel",
      "Aufrollen",
      "Steckdose"
    ]
  },
  {
    "equipmentId": "stromerzeuger",
    "difficulty": "Mittel",
    "taboo": [
      "Strom",
      "Benzin",
      "Aggregat",
      "Steckdose"
    ]
  },
  {
    "equipmentId": "flutlichtstrahler",
    "difficulty": "Mittel",
    "taboo": [
      "Licht",
      "Hell",
      "Ausleuchten",
      "Stativ"
    ]
  },
  {
    "equipmentId": "beleuchtungsstativ",
    "difficulty": "Mittel",
    "taboo": [
      "Licht",
      "Stativ",
      "Ausfahren",
      "Höhe"
    ]
  },
  {
    "equipmentId": "hydraulische-rettungsschere",
    "difficulty": "Mittel",
    "taboo": [
      "Schneiden",
      "Auto",
      "Hydraulik",
      "Unfall"
    ]
  },
  {
    "equipmentId": "hydraulischer-spreizer",
    "difficulty": "Mittel",
    "taboo": [
      "Spreizen",
      "Drücken",
      "Auto",
      "Hydraulik"
    ]
  },
  {
    "equipmentId": "rettungssatz",
    "difficulty": "Mittel",
    "taboo": [
      "Schere",
      "Spreizer",
      "Unfall",
      "Hydraulik"
    ]
  },
  {
    "equipmentId": "hebekissen",
    "difficulty": "Mittel",
    "taboo": [
      "Heben",
      "Luft",
      "Druck",
      "Last"
    ]
  },
  {
    "equipmentId": "tauchpumpe-tp-4",
    "difficulty": "Mittel",
    "taboo": [
      "Keller",
      "Wasser",
      "Pumpen",
      "Überflutung"
    ]
  },
  {
    "equipmentId": "saugkorb",
    "difficulty": "Mittel",
    "taboo": [
      "Saugen",
      "Sieb",
      "Gewässer",
      "Schmutz"
    ]
  },
  {
    "equipmentId": "trennschleifer",
    "difficulty": "Mittel",
    "taboo": [
      "Schneiden",
      "Funken",
      "Scheibe",
      "Metall"
    ]
  },
  {
    "equipmentId": "saebelsaege",
    "difficulty": "Mittel",
    "taboo": [
      "Sägen",
      "Blatt",
      "Akku",
      "Schnitt"
    ]
  },
  {
    "equipmentId": "ueberdruckluefter",
    "difficulty": "Mittel",
    "taboo": [
      "Lüften",
      "Rauch",
      "Gebläse",
      "Druck"
    ]
  },
  {
    "equipmentId": "uebergangsstueck",
    "difficulty": "Mittel",
    "taboo": [
      "Adapter",
      "Kupplung",
      "Verteiler",
      "Schlauch"
    ]
  },
  {
    "equipmentId": "mehrzweckleine",
    "difficulty": "Mittel",
    "taboo": [
      "Seil",
      "Ziehen",
      "Sichern",
      "Meter"
    ]
  },
  {
    "equipmentId": "oelbindemittel",
    "difficulty": "Mittel",
    "taboo": [
      "Öl",
      "Streuen",
      "Binden",
      "Straße"
    ],
    "excludeModes": [
      "Pantomime"
    ]
  },
  {
    "equipmentId": "fluchthaube",
    "difficulty": "Mittel",
    "taboo": [
      "Kopf",
      "Rauch",
      "Flucht",
      "Filter"
    ]
  },
  {
    "equipmentId": "feuerpatsche",
    "difficulty": "Mittel",
    "taboo": [
      "Schlagen",
      "Wald",
      "Gras",
      "Feuer"
    ]
  },
  {
    "equipmentId": "loeschrucksack",
    "difficulty": "Mittel",
    "taboo": [
      "Rücken",
      "Wasser",
      "Wald",
      "Sprühen"
    ]
  },
  {
    "equipmentId": "schlauchbruecke",
    "difficulty": "Mittel",
    "taboo": [
      "Schlauch",
      "Auto",
      "Überfahren",
      "Straße"
    ]
  },
  {
    "equipmentId": "zurrgurt",
    "difficulty": "Mittel",
    "taboo": [
      "Spannen",
      "Ratsche",
      "Sichern",
      "Ladung"
    ]
  },
  {
    "equipmentId": "werkzeugkoffer",
    "difficulty": "Mittel",
    "taboo": [
      "Werkzeug",
      "Koffer",
      "Schrauben",
      "Zange"
    ]
  },
  {
    "equipmentId": "tueroeffnungswerkzeug",
    "difficulty": "Mittel",
    "taboo": [
      "Tür",
      "Öffnen",
      "Schloss",
      "Spalt"
    ]
  },
  {
    "equipmentId": "multifunktionsleiter",
    "difficulty": "Mittel",
    "taboo": [
      "Leiter",
      "Klappen",
      "Vielseitig",
      "Steigen"
    ]
  },
  {
    "equipmentId": "unterbaumaterial",
    "difficulty": "Mittel",
    "taboo": [
      "Holz",
      "Keil",
      "Stützen",
      "Unterbauen"
    ]
  },
  {
    "equipmentId": "atemluftflasche",
    "difficulty": "Mittel",
    "taboo": [
      "Druck",
      "Luft",
      "Stahl",
      "Composite"
    ]
  },
  {
    "equipmentId": "kupplungsschluessel-abc",
    "difficulty": "Mittel",
    "taboo": [
      "Kupplung",
      "Lösen",
      "Schlüssel",
      "Schlauch"
    ]
  },
  {
    "equipmentId": "unterflurhydrantenschluessel",
    "difficulty": "Mittel",
    "taboo": [
      "Hydrant",
      "Straße",
      "Deckel",
      "Öffnen"
    ]
  },
  {
    "equipmentId": "verkehrssicherungskoffer",
    "difficulty": "Mittel",
    "taboo": [
      "Straße",
      "Absichern",
      "Warnen",
      "Koffer"
    ]
  },
  {
    "equipmentId": "schaummittelkanister",
    "difficulty": "Mittel",
    "taboo": [
      "Schaum",
      "Kanister",
      "Mittel",
      "Liter"
    ]
  },
  {
    "equipmentId": "auffangbehaelter",
    "difficulty": "Mittel",
    "taboo": [
      "Auffangen",
      "Flüssigkeit",
      "Wanne",
      "Leck"
    ]
  },
  {
    "equipmentId": "rettungstuch",
    "difficulty": "Mittel",
    "taboo": [
      "Tragen",
      "Patient",
      "Tuch",
      "Griffe"
    ]
  },
  {
    "equipmentId": "druckschlauch-d",
    "difficulty": "Mittel",
    "taboo": [
      "Schlauch",
      "Dünn",
      "Klein",
      "Kupplung"
    ]
  },
  {
    "equipmentId": "sammelstueck",
    "difficulty": "Schwer",
    "taboo": [
      "Verbinden",
      "Zusammenführen",
      "Leitung",
      "Zwei"
    ]
  },
  {
    "equipmentId": "stuetzkruemmer",
    "difficulty": "Schwer",
    "taboo": [
      "Krümmer",
      "Stützen",
      "Rohr",
      "Rückstoß"
    ]
  },
  {
    "equipmentId": "zumischer",
    "difficulty": "Schwer",
    "taboo": [
      "Schaum",
      "Mischen",
      "Schaummittel",
      "Wasser"
    ]
  },
  {
    "equipmentId": "wenderohr",
    "difficulty": "Schwer",
    "taboo": [
      "Rohr",
      "Drehen",
      "Wasser",
      "Werfer"
    ]
  },
  {
    "equipmentId": "mittelschaumrohr",
    "difficulty": "Schwer",
    "taboo": [
      "Schaum",
      "Rohr",
      "Mittel",
      "Verschäumung"
    ]
  },
  {
    "equipmentId": "schwerschaumrohr",
    "difficulty": "Schwer",
    "taboo": [
      "Schaum",
      "Rohr",
      "Schwer",
      "Verschäumung"
    ]
  },
  {
    "equipmentId": "mehrzweckstrahlrohr-b",
    "difficulty": "Schwer",
    "taboo": [
      "Rohr",
      "Strahl",
      "Sprüh",
      "B"
    ]
  },
  {
    "equipmentId": "mehrzweckstrahlrohr-c",
    "difficulty": "Schwer",
    "taboo": [
      "Rohr",
      "Strahl",
      "Sprüh",
      "C"
    ]
  },
  {
    "equipmentId": "mehrzweckzug",
    "difficulty": "Schwer",
    "taboo": [
      "Ziehen",
      "Seil",
      "Hebel",
      "Greifzug"
    ]
  },
  {
    "equipmentId": "rettungszylinder",
    "difficulty": "Schwer",
    "taboo": [
      "Drücken",
      "Hydraulik",
      "Auseinander",
      "Zylinder"
    ]
  },
  {
    "equipmentId": "rettungsplattform",
    "difficulty": "Schwer",
    "taboo": [
      "Plattform",
      "Auto",
      "Arbeiten",
      "Stabil"
    ]
  },
  {
    "equipmentId": "hydraulikaggregat",
    "difficulty": "Schwer",
    "taboo": [
      "Hydraulik",
      "Pumpe",
      "Druck",
      "Motor"
    ]
  },
  {
    "equipmentId": "hydraulikoel",
    "difficulty": "Schwer",
    "taboo": [
      "Öl",
      "Hydraulik",
      "Nachfüllen",
      "Kanister"
    ],
    "excludeModes": [
      "Pantomime"
    ]
  },
  {
    "equipmentId": "kaminkehrgeraet",
    "difficulty": "Schwer",
    "taboo": [
      "Kamin",
      "Schornstein",
      "Kehren",
      "Ruß"
    ]
  },
  {
    "equipmentId": "atemschutzueberwachungstafel",
    "difficulty": "Schwer",
    "taboo": [
      "Tafel",
      "Überwachen",
      "Zeit",
      "Trupp"
    ],
    "excludeModes": [
      "Pantomime"
    ]
  },
  {
    "equipmentId": "glasmanagement-set",
    "difficulty": "Schwer",
    "taboo": [
      "Glas",
      "Scheibe",
      "Säge",
      "Folie"
    ]
  },
  {
    "equipmentId": "kohlendioxidloescher",
    "difficulty": "Schwer",
    "taboo": [
      "Löscher",
      "Gas",
      "Kalt",
      "Elektro"
    ]
  }
];
